### PR TITLE
Fixes for latest GHC.

### PR DESCRIPTION
**Pull request by sighingnow**
Fixes for latest GHC and monad-control package.

Besides, could you please help to publish a new release of this package on hackage to make it usable with latest GHC (since this package is depended by other packages)?

### CODE REVIEW

**Comment by pepeiborra** [comment]
Thank you, this is awesome! 
Let me quickly set up some Github Actions for continuous integration to validate the changes.

**Comment by pepeiborra** [comment]
Could you rebase and force push?

**Comment by sighingnow** [comment]
Hi @pepeiborra All ci suites are green now!

**Comment by sighingnow** [comment]
Thanks for merging and cutting the new release!

**Pull request merged**
